<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.102.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SupermarketPOS.Core\SupermarketPOS.Core.csproj" />
    <ProjectReference Include="..\SupermarketPOS.Infrastructure\SupermarketPOS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
